name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Compilar o projeto
        run: mvn compile

      - name: Rodar os testes
        run: mvn test

      - name: Empacotar o projeto
        run: mvn package -DskipTests

      - name: Verificar arquivos gerados
        run: ls -lh target/

      - name: Salvar artefato
        uses: actions/upload-artifact@v4
        with:
          name: aplicacao-java
          path: target/*.jar
