name: Java CI/CD

on:
  push:
    branches: [ "main" ]  # Só faz o deploy na main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Compilar o projeto
        run: mvn compile

      - name: Rodar os testes
        run: mvn test

      - name: Empacotar o projeto (gera .jar)
        run: mvn package

      - name: Salvar artefato (arquivo .jar)
        uses: actions/upload-artifact@v4
        with:
          name: aplicacao-java
          path: target/*.jar
