name: Maven Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Build e Testes com Maven
        id: tests
        run: mvn clean install

      - name: Alerta de falha nos testes
        if: failure()
        run: |
          echo "::error::🚨 Atenção: A execução dos testes falhou!"

      - name: Alerta de sucesso nos testes
        if: success()
        run: |
          echo "::notice::✅ Sucesso: Todos os testes passaram!"
